table Stores
	lineageTag: c8e1f866-b9ef-4de4-bcbc-81654ddd6941

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: 9ee95e33-18f4-41bb-8ad6-c7852ff7f253
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 3d69e6cf-c4d1-42e2-bd6f-4471d81b8e3f
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 715a4776-eb88-4451-b994-84557154c48a
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Square Meters'
		dataType: int64
		formatString: 0
		lineageTag: 1b89ed3c-7037-42a0-8964-7d86deed97fa
		summarizeBy: sum
		sourceColumn: Square Meters

		annotation SummarizationSetBy = Automatic

	column 'Open Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9d4b5499-be9e-4ba1-8220-f8adc1c98d84
		summarizeBy: none
		sourceColumn: Open Date

		variation Variation
			isDefault
			relationship: 66d77bd5-6919-4c46-9228-53ffe45a4e87
			defaultHierarchy: LocalDateTable_762cab66-709e-4d30-bc63-753bb937812b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Channel
		dataType: string
		lineageTag: eb6758a3-b802-4052-8052-825168a14fab
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	partition Stores = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\sbixb\Downloads\Global+Electronics+Retailer\Stores.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"StoreKey", Int64.Type}, {"Country", type text}, {"State", type text}, {"Square Meters", Int64.Type}, {"Open Date", type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Open Date", type date}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "Channel", each if [StoreKey] = 0 then "Online" else "Physical Store")
				in
				    #"Added Custom"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

